"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Locale = "en" | "ar";
const translations: Record<string, string> = {
  "Services": "الخدمات", "Technologies": "التقنيات", "Solutions": "الحلول", "Examples": "أمثلة", "About us": "من نحن", "Contact us": "تواصل معنا", "Book consultation": "احجز استشارة", "Admin": "الإدارة", "Explore": "استكشف", "Company": "الشركة", "Talk to an expert": "تحدث مع خبير", "Client portal": "بوابة العملاء", "Start a conversation": "ابدأ محادثة", "Technology partner · since 2014": "شريك تقني · منذ 2014", "Make complex": "حوّل التعقيد", "useful.": "إلى قيمة.", "Tell us what matters": "أخبرنا بما يهمك", "About Antitude": "عن أنتيتيود", "Senior teams only": "فرق أولى فقط", "Outcome-led": "مدفوع بالنتائج", "No black boxes": "بلا صناديق سوداء", "Core services": "الخدمات الأساسية", "A sharp team for the messy middle.": "فريق حاسم للمراحل المعقدة.", "Technology radar": "رادار التقنية", "The stack is a means, not the strategy.": "التقنية وسيلة وليست استراتيجية.", "Industry perspective": "منظور القطاعات", "Context changes the answer.": "السياق يغير الإجابة.",   "Antitude helps CTOs, enterprise leaders, and founders turn difficult technology into clear, measurable momentum. Strategy, engineering, and responsible AI—working as one.": "تساعد أنتيتيود المديرين التقنيين وقادة المؤسسات والمؤسسين على تحويل التقنية الصعبة إلى زخم واضح وقابل للقياس. استراتيجية وهندسة وذكاء اصطناعي مسؤول — تعمل كفريق واحد.", "years making hard work clearer": "سنوات من توضيح العمل الصعب", "disciplines, one senior team": "مجالات معرفية، فريق أول واحد", "curiosity for what comes next": "فضول تجاه ما هو قادم", "Search examples": "ابحث في الأمثلة", "Search by capability or stack": "ابحث حسب القدرة أو التقنية", "Preview case": "معاينة الحالة", "View capabilities": "عرض القدرات", "No matching examples": "لا توجد أمثلة مطابقة", "Keep exploring": "تابع الاستكشاف", "Add to brief": "أضف إلى الطلب", "Core capabilities": "القدرات الأساسية", "All": "الكل", "Live radar": "الرادار المباشر", "Explore capabilities": "استكشف القدرات", "Explore technologies": "استكشف التقنيات", "Explore solutions": "استكشف الحلول", "Selected capability": "القدرة المختارة", "Related examples": "أمثلة ذات صلة", "Click a dot to explore": "اضغط على نقطة للاستكشاف", "AI systems": "أنظمة الذكاء الاصطناعي", "Cloud foundations": "أسس السحابة", "Data platforms": "منصات البيانات", "Responsible AI": "الذكاء الاصطناعي المسؤول", "Turn intelligence into decisions.": "حوّل الذكاء إلى قرارات.", "Build systems that keep moving.": "ابنِ أنظمة تواصل التقدم.", "Make signal easier to find.": "اجعل الوصول إلى الإشارة أسهل.", "Grounded copilots and evaluation": "مساعدات ذكية موثوقة وتقييم مستمر", "Resilient platforms and automation": "منصات مرنة وأتمتة عملية", "Pipelines and semantic layers": "خطوط بيانات وطبقات دلالية"
};
Object.assign(translations, {
  "Capabilities": "القدرات", "A partner for the parts that matter.": "شريك للأجزاء التي تصنع الفرق.", "From the first useful question to the last mile of adoption, we bring the people and practices required to make change stick.": "من أول سؤال مفيد إلى آخر خطوة في التبني، نوفر الخبرات والممارسات اللازمة لترسيخ التغيير.",
  "What we do": "ما نقدمه", "What we build with": "ما نبني به", "Product delivery": "تطوير المنتجات", "Connected systems": "الأنظمة المتصلة", "Confidence": "الثقة", "Platform": "المنصة", "Intelligence": "الذكاء", "Example outcome": "مثال على النتيجة", "Explore this capability": "استكشف هذه القدرة",
  "The technology partner for ambitious teams building what matters next.": "الشريك التقني للفرق الطموحة التي تبني ما يهم للمرحلة القادمة.", "Built for the next move": "مصمم للخطوة القادمة", "We bring strategy, engineering, and responsible AI together—without the black-box handoff.": "نجمع الاستراتيجية والهندسة والذكاء الاصطناعي المسؤول، دون تسليم غامض.", "Start a conversation": "ابدأ محادثة", "Five focused offers take work from useful question to dependable outcome.": "خمسة عروض مركزة تنقل العمل من سؤال مفيد إلى نتيجة موثوقة.", "Technologies support the service outcome: intelligence, products, connected systems, and resilient operations.": "تدعم التقنيات نتيجة الخدمة: الذكاء والمنتجات والأنظمة المتصلة والعمليات المرنة.", "Three case studies show the outcomes behind our services.": "توضح ثلاث دراسات حالة النتائج وراء خدماتنا.", "Technology becomes more useful when it respects the decisions, controls, and human moments in your industry.": "تصبح التقنية أكثر فائدة عندما تحترم القرارات والضوابط واللحظات الإنسانية في قطاعك.", "Explore services": "استكشف الخدمات", "Explore technologies": "استكشف التقنيات", "Explore examples": "استكشف الأمثلة", "Explore solutions": "استكشف الحلول", "Search examples": "ابحث في الأمثلة", "Preview case": "معاينة الحالة", "View capabilities": "عرض القدرات",   "Try a different capability, industry, or technology.": "جرّب قدرة أو قطاعاً أو تقنية مختلفة.", "Clear search": "مسح البحث", "Close example details": "إغلاق تفاصيل المثال", "delivery window": "فترة التنفيذ", "Core capabilities": "القدرات الأساسية",
  "Bring us the hard question.": "اطرح علينا السؤال الصعب.", "Less pitch. More signal.": "عرض أقل، إشارة أكثر.", "The first 30 minutes": "أول 30 دقيقة", "First name": "الاسم الأول", "Last name": "اسم العائلة", "Work email": "البريد الإلكتروني الوظيفي", "Phone": "الهاتف", "Preferred date": "التاريخ المفضل", "What are you working through?": "ما الذي تعمل عليه حالياً؟", "Send your note": "أرسل ملاحظتك", "We respond within one business day": "نرد خلال يوم عمل واحد", "A senior practitioner joins the call": "خبير أول ينضم إلى المكالمة", "No obligation, no generic deck": "بلا التزام وبلا عرض تقديمي عام", "By submitting, you agree that we can use this information to respond to your request.": "بإرسالك، فأنت توافق على استخدام هذه المعلومات للرد على طلبك.", "A sentence, a paragraph, or the messy version is perfect.": "جملة أو فقرة، أو حتى نسخة غير منسقة، كلها مقبولة.", "Tell us what is changing, what is stuck, or what you are trying to make possible. We will come prepared to be useful.": "أخبرنا ما الذي يتغير، أو ما الذي تتعثر فيه، أو ما الذي تحاول تحقيقه. سنأتي مستعدين لنكون مفيدين.", "You do not need a perfect brief. A little context is enough for us to understand the shape of the decision and bring the right perspective.": "لست بحاجة إلى مخطط مثالي، فسياق بسيط يكفي لفهم طبيعة القرار واختيار المنظور الصحيح.", "Thanks—we have your note and will be in touch shortly.": "شكراً لك، وصلتنا ملاحظتك وسنتواصل معك قريباً.",   "Sending...": "جارٍ الإرسال...", "(optional)": "(اختياري)", "See how we help": "اكتشف كيف نساعد", "Case in point": "حالة في الصميم", "Explore the opportunity": "استكشف الفرصة",
  "What we believe": "ما نؤمن به", "Our principles": "مبادئنا", "Find your next move.": "اكتشف خطوتك التالية.", "Discuss your version": "ناقش نسختك", "View all examples": "عرض كل الأمثلة", "Not sure where to start?": "لست متأكداً من أين تبدأ؟", "Capability deep dive": "غوص في القدرة", "Book a consultation": "احجز استشارة", "Case lens": "عدسة الحالة", "A point of view, not a template": "رؤية مخصصة وليست قالباً", "Share your context": "شارك سياقك", "Technology should accelerate ambition, not anchor it.": "يجب أن تسرّع التقنية الطموح، لا أن تكبّله.", "Built for the next move.": "مصمم للخطوة القادمة."
});

type LanguageContextValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (value: string) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  useEffect(() => {
    const saved = window.localStorage.getItem("antitude-locale") as Locale | null;
    if (saved === "ar" || saved === "en") setLocaleState(saved);
  }, []);
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.dataset.locale = locale;
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale: (next: Locale) => { setLocaleState(next); window.localStorage.setItem("antitude-locale", next); }, t: (value: string) => locale === "ar" ? translations[value] ?? value : value }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

export type { Locale };
