export type ExampleCategory = "Services" | "Solutions" | "Technologies";

export type Example = {
  id: string;
  title: string;
  eyebrow: string;
  category: ExampleCategory;
  description: string;
  capabilities: string[];
  stack: string[];
  timeline: string;
  media: string;
  metric: string;
};

export const examples: Example[] = [
  { id: "custom-web-app", title: "Custom Web Application Development", eyebrow: "Web Architecture", category: "Services", description: "Tailor-made, responsive web applications engineered for speed, scale, and longevity.", capabilities: ["Bespoke architecture tailored to unique business operations", "Single-page and server-rendered web applications", "Modular, maintainable TypeScript codebases"], stack: ["React", "Next.js", "TypeScript", "Node.js"], timeline: "6–12 weeks", media: "/images/technology-web-applications.png", metric: "Production-ready foundations" },
  { id: "frontend-development", title: "Frontend Development", eyebrow: "Frontend UI", category: "Services", description: "Pixel-perfect, high-performance user interfaces with smooth motion and accessibility.", capabilities: ["Figma-to-production design translation", "Fluid micro-interactions and GPU-accelerated motion", "Core Web Vitals tuning"], stack: ["React", "Next.js", "TypeScript", "Tailwind CSS"], timeline: "4–8 weeks", media: "/images/technology-web-applications.png", metric: "Sub-1.2s LCP target" },
  { id: "saas-platform", title: "SaaS Application Development", eyebrow: "SaaS Platform", category: "Solutions", description: "Scalable subscription software platforms built for recurring revenue and high availability.", capabilities: ["Subscription billing and webhook flows", "Workspace provisioning and onboarding", "Granular team roles and permissions"], stack: ["Next.js", "React", "Node.js", "TypeScript"], timeline: "8–16 weeks", media: "/images/solution-finance.png", metric: "Built for recurring revenue" },
  { id: "admin-dashboard", title: "Admin Dashboards & Management Systems", eyebrow: "Admin Dashboard", category: "Solutions", description: "High-density operational cockpits with real-time analytics and data control.", capabilities: ["Advanced filtering, sorting, and inline editing", "Real-time KPI cards and data visualizations", "Bulk actions and scheduled reporting"], stack: ["React", "TypeScript", "TanStack Table", "Recharts"], timeline: "5–10 weeks", media: "/images/solution-energy.png", metric: "One source of operational truth" },
  { id: "customer-portal", title: "Customer Portals & Self-Service Platforms", eyebrow: "Customer Portal", category: "Solutions", description: "Secure, intuitive digital hubs for clients to access services, documents, and support.", capabilities: ["Secure authentication and 2FA", "Interactive project milestone tracking", "Encrypted document repositories"], stack: ["React", "Next.js", "TypeScript", "Tailwind CSS"], timeline: "5–10 weeks", media: "/images/solution-healthcare.png", metric: "Self-service without friction" },
  { id: "ecommerce", title: "E-Commerce Platforms", eyebrow: "E-Commerce", category: "Solutions", description: "High-conversion digital storefronts with rapid checkout and inventory synchronization.", capabilities: ["Headless catalog with faceted search", "Single-page checkout for mobile users", "Multi-gateway payment processing"], stack: ["Next.js", "React", "TypeScript", "Node.js"], timeline: "6–12 weeks", media: "/images/solution-retail.png", metric: "Conversion-minded by design" },
  { id: "ai-applications", title: "AI-Powered Application Development", eyebrow: "AI Applications", category: "Technologies", description: "Custom applications enhanced with generative AI, semantic intelligence, and LLMs.", capabilities: ["Grounded LLM application engineering", "RAG architecture for company documents", "Vector indexing and semantic search"], stack: ["Gemini API", "TypeScript", "Python", "LangChain"], timeline: "6–12 weeks", media: "/images/technology-generative-ai.png", metric: "Useful intelligence, with guardrails" },
  { id: "ai-chatbots", title: "AI Chatbots & Conversational Assistants", eyebrow: "AI Chatbots", category: "Technologies", description: "24/7 intelligent conversational agents with verified data grounding and tool execution.", capabilities: ["Routine tier-1 inquiry automation", "Strict grounding in product documentation", "Order lookup, record updates, and email tools"], stack: ["Gemini 2.5 Flash", "TypeScript", "Node.js", "Vector DB"], timeline: "4–8 weeks", media: "/images/technology-automation.png", metric: "Up to 75% routine requests automated" },
  { id: "ai-agents", title: "AI Agents", eyebrow: "AI Agents", category: "Technologies", description: "Autonomous AI agents that plan, reason, and complete multi-step business objectives.", capabilities: ["Multi-agent orchestration", "Iterative self-correction and tool invocation", "Web browsing and structured research"], stack: ["Python", "TypeScript", "LangGraph", "Gemini Models"], timeline: "6–12 weeks", media: "/images/technology-generative-ai.png", metric: "From prompt to completed objective" },
  { id: "knowledge-ai", title: "AI-Powered Search & Knowledge Assistants", eyebrow: "Knowledge AI", category: "Technologies", description: "Instant semantic search across company handbooks, PDFs, codebases, and databases.", capabilities: ["Intent-aware semantic vector search", "Automated document ingestion", "Answers with direct source citations"], stack: ["pgvector", "Pinecone", "TypeScript", "Python"], timeline: "5–10 weeks", media: "/images/technology-data-platforms.png", metric: "Answers people can verify" },
  { id: "systems-integration", title: "Systems Integration", eyebrow: "Systems Bridge", category: "Services", description: "Connecting legacy on-premises databases, ERPs, and cloud microservices.", capabilities: ["Event-driven message architecture", "Legacy database synchronization", "Change Data Capture pipelines"], stack: ["Kafka", "RabbitMQ", "Node.js", "TypeScript"], timeline: "6–12 weeks", media: "/images/technology-cloud-native.png", metric: "Legacy systems, moving together" },
  { id: "process-automation", title: "Business Process Automation", eyebrow: "Process Auto", category: "Services", description: "Intelligent automation eliminating repetitive workflows and cross-department busywork.", capabilities: ["Lead capture and customer onboarding automation", "Webhook connectors across business tools", "Scheduled reconciliation jobs"], stack: ["Node.js", "TypeScript", "BullMQ", "Redis"], timeline: "3–6 weeks", media: "/images/technology-automation.png", metric: "Less repetition, more momentum" },
];
